# Exercise 3.4 - Using Google Distroless
FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

# Use distroless image
FROM gcr.io/distroless/static:nonroot

COPY --from=builder /app/main /main

EXPOSE 8080
ENTRYPOINT ["/main"]