#Exercise-01
#Date- 22 feb 2026
#Purpose: Serve static html files using nginx
FROM nginx:alpine

COPY index.html /usr/share/nginx/html/

#Expose port 80 for outside world
EXPOSE 80

# Nginx starts automatically - no CMD needed as it's inherited from base image

